"""Stable numerical defaults shared by the Production optimizer kernel."""

from __future__ import annotations

from pathlib import Path


POLYGON_ROOT = Path(__file__).resolve().parents[2]

DEFAULT_ANCHORS_PER_CONTOUR = 48
DEFAULT_RECALL_MIN = 0.97
DEFAULT_MAX_GAP = 30
DEFAULT_DP_EVAL_SCALE = 1.0
DEFAULT_DP_EVAL_PAD = 8
DEFAULT_SURROGATE_POOL_FACTOR = 2.0
DEFAULT_SURROGATE_PEAK_FACTOR = 1.2
DEFAULT_SURROGATE_NEIGHBOR_RADIUS = 1
DEFAULT_SURROGATE_SHAPE_WEIGHT = 0.15
DEFAULT_SALIENCY_SHAPE_ETA = 0.5
DEFAULT_SALIENCY_AREA_ETA = 0.45
DEFAULT_PENALTY_BINARY_STEPS = 12
DEFAULT_PENALTY_MAX = 1024.0
DEFAULT_RECALL_BUDGET_BINARY_STEPS = 8
DEFAULT_RECALL_BUDGET_MAX_MU = 64.0
DEFAULT_PATH_RECALL_VIOLATION_WEIGHT = 64.0
DEFAULT_SHAPE_SWITCH_WEIGHT = 2.0
DEFAULT_SHAPE_DISTANCE_WEIGHT = 0.4
DEFAULT_SHAPE_UPDATE_THRESHOLD_RATIO = 0.09
DEFAULT_SHAPE_PENALTY_ADAPT_GAIN = 1.25
DEFAULT_SHAPE_DISTANCE_RELIEF = 1.10
DEFAULT_SHAPE_SWITCH_RELIEF = 0.45
DEFAULT_SHAPE_DISTANCE_MIN_SCALE = 0.10
DEFAULT_SHAPE_SWITCH_MIN_SCALE = 0.45
DEFAULT_DYNAMIC_MAX_GAP_FACTOR = 4.0
DEFAULT_INTERVAL_IOU_WEIGHT = 1.0
DEFAULT_EXACT_RECALL_REPAIR_MAX_PASSES = 4
DEFAULT_EXACT_RECALL_REPAIR_TOPK = 3
DEFAULT_EXACT_RECALL_REPAIR_SCALE_DELTAS = (
    0.01,
    0.02,
    0.04,
    0.06,
    0.08,
    0.10,
    0.12,
)
DEFAULT_ADAPTIVE_ANCHOR_COUNTS = False
DEFAULT_ADAPTIVE_POINT_QUANTILE = 0.95
DEFAULT_ADAPTIVE_POINT_OFFSET = 2
DEFAULT_MIN_ANCHORS_PER_CONTOUR = 4
DEFAULT_PREDICTOR_BATCH_SIZE = 256
DEFAULT_PREDICTOR_DEVICE = "cuda"
DEFAULT_GAPFILL_ENABLED = True
DEFAULT_GAPFILL_MAX_GAP = 30
DEFAULT_GAPFILL_TEMP_POINTS = 128
DEFAULT_MAX_RUN_FRAMES = 30000
DEFAULT_RUN_OVERLAP_FRAMES = 900
DEFAULT_POINT_PREDICTOR_MODEL_DIR = (
    POLYGON_ROOT
    / "experiments"
    / "linear_polygon_bezier_workspace_20260410"
    / "output"
    / "mask_point_predictor_wide96_20260411"
)
